#!/bin/bash
! [ -f pdos_tot ] && ~/easy_script/splitdos.pl 


LSORBIT=`cat OUTCAR | grep "LSORBIT" | awk '{print $3}'`
[ "$LSORBIT" = "T" ]  && prefix="`cat DOSCAR | head -n 5 | tail -1 | awk '{print $1}'`""_soc" ||  prefix="`cat DOSCAR | head -n 5 | tail -1 | awk '{print $1}'`""_mn"

##################  for ia (POSCAR infor)  #######################
cat > merger_data.pl << EOF
#!/usr/bin/perl

open(info,">ia");
select info;

	open(POSCAR,"POSCAR");
	for(\$i=0;\$i<5;\$i++) {
	  \$_=<POSCAR>;
	}

	\$_=<POSCAR>;
	@atmnam=split;print "@atmnam \n";
	\$_=<POSCAR>;
	@atmnum=split;print "@atmnum \n";
	\$nspec=@atmnam;print "\$nspec \n";
	\$tot_num=\$atmnum[0]+\$atmnum[1]; print "\$tot_num \n";
	close(POSCAR);
select STDOUT;
close(info);


EOF

perl merger_data.pl
rm merger_data.pl
#################### for dos_orbit.dat && dos_atom.dat   ##################################
mv pdos_tot tot_pdos
j=0;
for i in pdos_*
   do 
      if [ $j = 0 ]
         then
		cat $i | sed -e '/^#/d' > dos_orbit.dat
      else
      		cat $i | sed -e '/^#/d' > pdos_temp
      		paste  dos_orbit.dat pdos_temp > dos_atom_temp
                cat dos_atom_temp > dos_orbit.dat
      fi
    j=` expr $j + 10` 
    printf "$i \n"
   done
rm *temp*
mv tot_pdos pdos_tot 

nspec=`cat ia | head -n 3 |  tail -1 | awk '{print $1}'` 
for i in `seq 1 $nspec`
    do
         
         atmnam=`cat ia | head -n 1 | awk '{print $'$i'}'`
         atstr="dos_$atmnam.dat"
         search_name="pdos_$atmnam*"
         m=0
         for h in $search_name
		do
                    if [ $m = 0 ]
                         then
		               cat $h | sed -e '/^#/d' > $atstr	
                    else	
                               cat $h  | sed -e '/^#/d' > pdos_temp
      		               paste  $atstr pdos_temp > dos_atom_temp
                               cat dos_atom_temp > $atstr
                    fi
      m=` expr $m + 1` 
                done
rm *temp*

temp=`cat $atstr | head -n 1 | wc -w`
echo -n "$temp " >> ia
unset temp
    done
#################### fot gnuplot   ##################################

Efermi=`cat OUTCAR | grep "E-fermi"| awk '{print $3}'`
#prefix=`cat DOSCAR | head -n 5 | tail -1 | awk '{print $1}'`
dos_energy='$1';
dos_weight='2';
lab0='tot-dos'
lab1='s'
lab2='p'
lab3='d'
#lab4='f'
#str_data=("str_data_s" "str_data_px" "str_data_py" "str_data_pz" "str_data_dxy" "str_data_dyz" "str_data_dxz" "str_data_dx2-y2" "str_data_dz2")
str_data_s=""
str_data_px=""; 
str_data_py=""; 
str_data_pz=""
str_data_dxy=""; 
str_data_dyz=""; 
str_data_dxz="";
str_data_dx2y2=""
str_data_dz2=""


for k in `seq 2 10`
    do
	for i in `seq $k 10 $j`
	    do 
	       [ $i -eq 2 ] && [ $k -eq 2 ] && str_data_s="\$$i"
	       [ $i -ne 2 ] && [ $k -eq 2 ] && str_data_s="$str_data_s+\$$i"

	       [ $i -eq 3 ] && [ $k -eq 3 ] && str_data_px="\$$i"
	       [ $i -ne 3 ] && [ $k -eq 3 ] && str_data_px="$str_data_px+\$$i"	

	       [ $i -eq 4 ] && [ $k -eq 4 ] && str_data_py="\$$i"
	       [ $i -ne 4 ] && [ $k -eq 4 ] && str_data_py="$str_data_py+\$$i"	

	       [ $i -eq 5 ] && [ $k -eq 5 ] && str_data_pz="\$$i"
	       [ $i -ne 5 ] && [ $k -eq 5 ] && str_data_pz="$str_data_pz+\$$i"	

	       [ $i -eq 6 ] && [ $k -eq 6 ] && str_data_dxy="\$$i"
	       [ $i -ne 6 ] && [ $k -eq 6 ] && str_data_dxy="$str_data_dxy+\$$i"	

	       [ $i -eq 7 ] && [ $k -eq 7 ] && str_data_dyz="\$$i"
	       [ $i -ne 7 ] && [ $k -eq 7 ] && str_data_dyz="$str_data_dyz+\$$i"

	       [ $i -eq 8 ] && [ $k -eq 8 ] && str_data_dxz="\$$i"
	       [ $i -ne 8 ] && [ $k -eq 8 ] && str_data_dxz="$str_data_dxz+\$$i"

	       [ $i -eq 9 ] && [ $k -eq 9 ] && str_data_dx2y2="\$$i"
	       [ $i -ne 9 ] && [ $k -eq 9 ] && str_data_dx2y2="$str_data_dx2y2+\$$i"

	       [ $i -eq 10 ] && [ $k -eq 10 ] && str_data_dz2="\$$i"
	       [ $i -ne 10 ] && [ $k -eq 10 ] && str_data_dz2="$str_data_dz2+\$$i"
	    done
     done
#echo "$str_data_s \n"
#echo "$str_data_px \n"
#echo "$str_data_py \n"
#echo "$str_data_pz \n"
#echo "$str_data_dxy \n"
#echo "$str_data_dyz \n"
#echo "$str_data_dxz \n"
#echo "$str_data_dx2y2 \n"
#echo "$str_data_dz2 \n"

str_data_p="$str_data_px+$str_data_py+$str_data_pz"
str_data_d="$str_data_dxy+$str_data_dyz+$str_data_dxz+$str_data_dx2y2+$str_data_dz2"

############### plot  pdos #######################
output_name="$prefix""_dos.eps"
cat > plot.$prefix.dos << EOF

set key right top
set xlabel'Energy(eV)'
set ylabel'DOS(eV^{-1}/cell)'
set xrange[-6:15];set xtics 5;set mxtics 5; 
set yrange[0:15];set ytics 5;
set arrow from 0.0,0.0 to 0.0,15.0 nohead lt 0

plot 'pdos_tot' u ($dos_energy-$Efermi) :$dos_weight title '$lab0' w l , 'dos_orbit.dat'  u ($dos_energy- $Efermi):($str_data_s ) title '$lab1' w l, "" u ($dos_energy- $Efermi):($str_data_p ) title '$lab2' w l, "" u ($dos_energy- $Efermi):($str_data_d ) title '$lab3' w l




set terminal postscript eps color enh
set output "$output_name"
#set terminal png
#set output "dos.png"
replot

EOF
################ plot dos for atoms   ###################
atom_num=`cat ia | head -n 4 | tail -1 | awk '{print $1}'`
J=($(cat ia | head -n 5 | tail -1))
str_data_s=""
str_data_px=""; 
str_data_py=""; 
str_data_pz=""
str_data_dxy=""; 
str_data_dyz=""; 
str_data_dxz="";
str_data_dx2y2=""
str_data_dz2=""

for n in `seq 1 $nspec`
    do
	for k in `seq 2 10`
	    do
		for i in `seq $k 10 ${J[$n-1]}`
		    do 
		       [ $i -eq 2 ] && [ $k -eq 2 ] && str_data_s="\$$i"
		       [ $i -ne 2 ] && [ $k -eq 2 ] && str_data_s="$str_data_s+\$$i"

		       [ $i -eq 3 ] && [ $k -eq 3 ] && str_data_px="\$$i"
		       [ $i -ne 3 ] && [ $k -eq 3 ] && str_data_px="$str_data_px+\$$i"	

		       [ $i -eq 4 ] && [ $k -eq 4 ] && str_data_py="\$$i"
		       [ $i -ne 4 ] && [ $k -eq 4 ] && str_data_py="$str_data_py+\$$i"	

		       [ $i -eq 5 ] && [ $k -eq 5 ] && str_data_pz="\$$i"
		       [ $i -ne 5 ] && [ $k -eq 5 ] && str_data_pz="$str_data_pz+\$$i"	

		       [ $i -eq 6 ] && [ $k -eq 6 ] && str_data_dxy="\$$i"
		       [ $i -ne 6 ] && [ $k -eq 6 ] && str_data_dxy="$str_data_dxy+\$$i"	

		       [ $i -eq 7 ] && [ $k -eq 7 ] && str_data_dyz="\$$i"
		       [ $i -ne 7 ] && [ $k -eq 7 ] && str_data_dyz="$str_data_dyz+\$$i"

		       [ $i -eq 8 ] && [ $k -eq 8 ] && str_data_dxz="\$$i"
		       [ $i -ne 8 ] && [ $k -eq 8 ] && str_data_dxz="$str_data_dxz+\$$i"

		       [ $i -eq 9 ] && [ $k -eq 9 ] && str_data_dx2y2="\$$i"
		       [ $i -ne 9 ] && [ $k -eq 9 ] && str_data_dx2y2="$str_data_dx2y2+\$$i"

		       [ $i -eq 10 ] && [ $k -eq 10 ] && str_data_dz2="\$$i"
		       [ $i -ne 10 ] && [ $k -eq 10 ] && str_data_dz2="$str_data_dz2+\$$i"
		  done
	    done
                   
	str_data_p="$str_data_px+$str_data_py+$str_data_pz"
	str_data_d="$str_data_dxy+$str_data_dyz+$str_data_dxz+$str_data_dx2y2+$str_data_dz2"
        str_data_all="$str_data_s+$str_data_p+$str_data_d"
        echo  $str_data_s  >> data_temp_s
        echo  $str_data_p  >> data_temp_p
        echo  $str_data_d  >> data_temp_d
        echo  $str_data_all >> data_temp_all
     done

#cat data_temp_all



         atmnam=`cat ia | head -n 1 | awk '{print $'$i'}'`
         atstr="dos_$atmnam.dat"
         search_name="pdos_$atmnam*"
str_temp="'pdos_tot' u ($dos_energy-$Efermi) :$dos_weight title '$lab0' w l"

for i in `seq 1 $nspec`
    do
	atmnam=`cat ia | head -n 1 | awk '{print $'$i'}'`
        atstr="dos_$atmnam.dat"
        lab="$atmnam""-dos"
        str_data_all=`cat data_temp_all | head -n $i | tail -1`
        str_temp_atom=" ,'$atstr' u ($dos_energy-$Efermi) :($str_data_all) title '$lab' w l "
        str_temp="$str_temp""$str_temp_atom"
        
    done
#echo $str_temp
rm data_temp_*
rm ia
output_name="$prefix""_dos_atom.eps"
cat > plot.$prefix.dos_atom << EOF

set key right top
set xlabel'Energy(eV)'
set ylabel'DOS(eV^{-1}/cell)'
set xrange[-6:15];set xtics 5;set mxtics 5; 
set yrange[0:15];set ytics 5;
set arrow from 0.0,0.0 to 0.0,15.0 nohead lt 0

plot $str_temp

set terminal postscript eps color enh
set output "$output_name"
#set terminal png
#set output "dos_atom.png"
replot

EOF
echo "plot plot.$prefix.dos..."
gnuplot plot.$prefix.dos
echo "plot.$prefix.dos_atom..."
gnuplot plot.$prefix.dos_atom
